# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: firefly.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='firefly.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rfirefly.proto\",\n\x05Phase\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x12\r\n\x05phase\x18\x03 \x01(\x01\"=\n\rPhasesRequest\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x12\x16\n\x06phases\x18\x03 \x03(\x0b\x32\x06.Phase\"(\n\x0ePhasesResponse\x12\x16\n\x06phases\x18\x01 \x03(\x0b\x32\x06.Phase\"\x11\n\x0fPositionRequest\"(\n\x10PositionResponse\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x32w\n\x0e\x46ireflyService\x12/\n\nSendPhases\x12\x0e.PhasesRequest\x1a\x0f.PhasesResponse\"\x00\x12\x34\n\x0bGetPosition\x12\x10.PositionRequest\x1a\x11.PositionResponse\"\x00\x62\x06proto3'
)




_PHASE = _descriptor.Descriptor(
  name='Phase',
  full_name='Phase',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='Phase.x', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='Phase.y', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='phase', full_name='Phase.phase', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=61,
)


_PHASESREQUEST = _descriptor.Descriptor(
  name='PhasesRequest',
  full_name='PhasesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='PhasesRequest.x', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='PhasesRequest.y', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='phases', full_name='PhasesRequest.phases', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=124,
)


_PHASESRESPONSE = _descriptor.Descriptor(
  name='PhasesResponse',
  full_name='PhasesResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='phases', full_name='PhasesResponse.phases', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=126,
  serialized_end=166,
)


_POSITIONREQUEST = _descriptor.Descriptor(
  name='PositionRequest',
  full_name='PositionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=168,
  serialized_end=185,
)


_POSITIONRESPONSE = _descriptor.Descriptor(
  name='PositionResponse',
  full_name='PositionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='PositionResponse.x', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='PositionResponse.y', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=187,
  serialized_end=227,
)

_PHASESREQUEST.fields_by_name['phases'].message_type = _PHASE
_PHASESRESPONSE.fields_by_name['phases'].message_type = _PHASE
DESCRIPTOR.message_types_by_name['Phase'] = _PHASE
DESCRIPTOR.message_types_by_name['PhasesRequest'] = _PHASESREQUEST
DESCRIPTOR.message_types_by_name['PhasesResponse'] = _PHASESRESPONSE
DESCRIPTOR.message_types_by_name['PositionRequest'] = _POSITIONREQUEST
DESCRIPTOR.message_types_by_name['PositionResponse'] = _POSITIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Phase = _reflection.GeneratedProtocolMessageType('Phase', (_message.Message,), {
  'DESCRIPTOR' : _PHASE,
  '__module__' : 'firefly_pb2'
  # @@protoc_insertion_point(class_scope:Phase)
  })
_sym_db.RegisterMessage(Phase)

PhasesRequest = _reflection.GeneratedProtocolMessageType('PhasesRequest', (_message.Message,), {
  'DESCRIPTOR' : _PHASESREQUEST,
  '__module__' : 'firefly_pb2'
  # @@protoc_insertion_point(class_scope:PhasesRequest)
  })
_sym_db.RegisterMessage(PhasesRequest)

PhasesResponse = _reflection.GeneratedProtocolMessageType('PhasesResponse', (_message.Message,), {
  'DESCRIPTOR' : _PHASESRESPONSE,
  '__module__' : 'firefly_pb2'
  # @@protoc_insertion_point(class_scope:PhasesResponse)
  })
_sym_db.RegisterMessage(PhasesResponse)

PositionRequest = _reflection.GeneratedProtocolMessageType('PositionRequest', (_message.Message,), {
  'DESCRIPTOR' : _POSITIONREQUEST,
  '__module__' : 'firefly_pb2'
  # @@protoc_insertion_point(class_scope:PositionRequest)
  })
_sym_db.RegisterMessage(PositionRequest)

PositionResponse = _reflection.GeneratedProtocolMessageType('PositionResponse', (_message.Message,), {
  'DESCRIPTOR' : _POSITIONRESPONSE,
  '__module__' : 'firefly_pb2'
  # @@protoc_insertion_point(class_scope:PositionResponse)
  })
_sym_db.RegisterMessage(PositionResponse)



_FIREFLYSERVICE = _descriptor.ServiceDescriptor(
  name='FireflyService',
  full_name='FireflyService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=229,
  serialized_end=348,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendPhases',
    full_name='FireflyService.SendPhases',
    index=0,
    containing_service=None,
    input_type=_PHASESREQUEST,
    output_type=_PHASESRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetPosition',
    full_name='FireflyService.GetPosition',
    index=1,
    containing_service=None,
    input_type=_POSITIONREQUEST,
    output_type=_POSITIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_FIREFLYSERVICE)

DESCRIPTOR.services_by_name['FireflyService'] = _FIREFLYSERVICE

# @@protoc_insertion_point(module_scope)
